# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: "nginx -2"
  namespace: n1
  labels:
    app: "nginx -2"
spec:
  containers:
  - name: nginx -2
    image: "nginx:alpine"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: VARIABLE_1
      value: "VALOR 1"
    - name: VARIABLE_2
      value: "VALOR 2"
    - name: DD_AGEN_HOST
      valueFrom:
        fieldRef:
          fieldPath:
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
    ports:
    - containerPort: 80
      name: http
    
---
